require 'swamp/version'
require 'swamp/assertions'
require 'swamp/setup'
require 'swamp/interface'
require 'swamp/evaluator'
require 'swamp/base'
require 'swamp/elements'
require 'swamp/wrapper'
require 'swamp/element'
require 'swamp/fields'
require 'swamp/field'
require 'swamp/buttons'
require 'swamp/button'
require 'swamp//builders/basic'
require 'swamp/formatter'
require 'swamp/input_buttons'
require 'swamp/input_button'
require 'swamp/select_boxes'
require 'swamp/select_box'
require 'swamp/complex_select_box'
require 'swamp/links'
require 'swamp/link'
require 'swamp/scopes/source'
require 'swamp/scopes/page'
require 'swamp/scopes/scope'

module Swamp
end
